use_directory_urls: True

plugins:
  - search
  - open-in-new-tab:
      add_icon: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list

nav:
  - Home: "README.md"
